name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup
        run: |
          curl -sL https://github.com/youyo/github-actions-comment/releases/download/v0.1.1/ghc_0.1.1_Linux_x86_64 -o ghc
          chmod +x ghc
      - name: Execute
        run: |
          ./ghc --title 'Test' --body `env`
