name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup
        run: |
          curl -sL https://github.com/youyo/github-actions-comment/releases/download/v0.1.1/ghc_0.1.1_Linux_x86_64 -o ghc
          chmod +x ghc
      - name: Execute
        env:
          TEST_MESSAGE: 'test-message'
        run: |
          ./ghc --title 'Test' --body `w`
          ./ghc --title 'Test' --body `id`
          ./ghc --title 'Test' --body `pwd`
          ./ghc --title 'Test' --body `ls`
          echo "100\n200\n300" > text
          ./ghc --title 'Test' --body `cat text`
